config/routes.rb
Onboard::Application.routes.draw do

  # to fit in with omniauth's callback urls
  get "/auth/:provider/callback" => "social_logins#create"

  # static pages
  get "/about" => "contents#about"
  get "/terms-and-conditions" => "contents#terms", as: "terms"
  get "/privacy" => "contents#privacy"

  # this is where our URLs of our webapp are set
  resources :users
  resources :jobs do
    resources :submissions
    resource :payment
  end


  # because i don't want to login twice as a user
  # lets use a singular resource
  resource :session

  root "jobs#index"

end

app/models/job.rb
class Job < ActiveRecord::Base

	belongs_to :user
	has_many :submissions

	validates :title, presence: true, length: { minimum: 5 }
	validates :description, presence: true
	validates :company_name, presence: true
	validates :company_tagline, presence: true
	validates :location, presence: true

	geocoded_by :location
	after_validation :geocode

	has_attached_file :company_logo, styles: { large: "300x300#", medium: "100x100#" }
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  # the user must be signed in
  # for everything EXCEPT from the index and show (method in ApplicationController)
  before_action :require_user, except: [:index, :show]


  def index
    @jobs = Job.order("stripe_token asc, created_at desc")
    # if i wanted to find all of my jobs
    # it would be :
    # @jobs = current_user.jobs.all
  end


  def show
    # not current_user.jobs because it can be ANYONE'S job
    @job = Job.find(params[:id])
  end


  def new
    # @job = Job.new
	  # because we want the job attached to a user, the above won't work, instead we do this:
    @job = current_user.jobs.new
  end

  def create
    @job = current_user.jobs.new(job_params)

    if @job.save
      flash[:success] = "Job added"
      redirect_to job_path(@job)
    else
      render :new
    end
  end


  def edit
    @job = current_user.jobs.find(params[:id])
  end


  def update
    @job = current_user.jobs.find(params[:id])
    if @job.update(job_params)
      flash[:success] = "Job updated"
      redirect_to job_path(@job)
    else
      render :edit
    end
  end


  def destroy
    @job = current_user.jobs.find(params[:id])
    @job.destroy
    flash[:success] = "Job deleted"
    redirect_to root_path
  end
  

  def job_params
    params.require(:job).permit(:title, :description, :company_name, :company_url, :company_tagline, :location, :phone, :application_deadline, :salary, :company_logo)
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>

	<%= f.input :title %>
	<%= f.input :description %>

	<%= f.input :company_name %>
	<%= f.input :company_url, label: "Company Website", as: :string%>
	<%= f.input :company_tagline %>
	<%= f.input :company_logo %>

	<%= f.input :location %>
	<%= f.input :phone, as: :string %>
	<%= f.input :application_deadline %>
	<%= f.input :salary %>

	<%= f.button :submit %>

<% end %>

app/views/jobs/edit.html.erb
<div class = "eight columns offset-by-two">

	<h2>Edit this Job</h2>	

	<%= render "form" %>

</div>

app/views/jobs/index.html.erb
<section class="nine columns bordered">


    <div class="jobslist">
      <% @jobs.each do |job| %>
        <div class="single_job group">

          <%= link_to job_path(job) do %>

            <% if job.company_logo.present? %>
              <%= image_tag job.company_logo(:medium), class: "company_logo" %>
            <% end %>

            <div class="job_details <% if job.stripe_token.present? %> featured<% end %>">
              <h3><%= job.title %></h3>
              <p><%= job.company_name %><br> <%= job.location %></p>
            </div>

            <div class="job_actions">
              <p>Salary: <%= job.salary %></p>
              <p>Added <%= job.created_at.to_date.to_formatted_s(:long) %></p>
              <p>Submit by <%= job.application_deadline %></p>
            </div>
          <% end %>


        </div>
      <% end %>

    </div>
</section>

<aside class="three columns bordered">
  <%= form_tag root_path, method: :get, class: "search_form" do |f| %>
    <%= text_field_tag :location, params[:location], { placeholder: "Location", class: "location_search" } %>
   <% end %>

  <h3>Category</h3>
    <ul>
    CATEGORY
    </ul>

  <h3>Job type</h3>
    <ul>

    JOB TYPE
    </ul>


</aside>

app/views/jobs/new.html.erb
<div class = "eight columns offset-by-two">

	<h2>Add a Job</h2>	

	<%= render "form" %>

</div>

app/views/jobs/show.html.erb
<div class="job_show">

	<div class="row">

		<div class="four columns offset-by-four">

			<h3><%= @job.title %></h3>
			<h4><%= @job.company_name %></h4>
			<h4><%= @job.location %></h4>

		</div>

	</div>

	<div class="row">

		<div class="eight columns offset-by-two">
			
			<blockquote><%= @job.company_tagline %></blockquote>

			<%= md @job.description %>

			<p>
				Salary: <%= @job.salary %><br />
				Website: <a href="<%= @job.company_url %>"><%= @job.company_url %></a><br />
				Application deadline: <%= @job.application_deadline %>
			</p>
		
		</div>

	</div>

	<div class="row">
		<div class="ten columns offset-by-one">
			<div class="map" data-lat="<%= @job.latitude %>" data-long="<%= @job.longitude %>"></div>
		</div>
	</div>

	<div class="row">
		<div class="ten columns offset-by-one">
			<%= link_to "Apply", new_job_submission_path(@job), class: "button" %>
			<% if current_user.present? and current_user == @job.user %>
				<%= link_to "Feature this job", new_job_payment_path(@job), class: "button" %>
				<%= link_to "Edit", edit_job_path(@job), class: "button" %>
				<%= link_to "Delete", job_path(@job), method: :delete, class: "button", confirm: "Are you sure?" %>
			<% end %>
		</div>
	</div>

	<% if current_user.present? and current_user == @job.user %>
		<div class="row">
			<div class="six columns offset-by-three">
				<h3>Submissions for this job</h3>

				<ul>
					<% @job.submissions.each do |s| %>
						<li>
							<%= link_to s.user.name, job_submission_path(@job, s) %>
						</li>
					<% end %>
				</ul>
				
			</div>
		</div>
	<% end %>


</div>