config/routes.rb
Onboard::Application.routes.draw do

  # to fit in with omniauth's callback urls
  get "/auth/:provider/callback" => "social_logins#create"

  # static pages
  get "/about" => "contents#about"
  get "/terms-and-conditions" => "contents#terms", as: "terms"
  get "/privacy" => "contents#privacy"

  # this is where our URLs of our webapp are set
  resources :users
  resources :jobs do
    resources :submissions
    resource :payment
  end


  # because i don't want to login twice as a user
  # lets use a singular resource
  resource :session

  root "jobs#index"

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  before_action :require_user

  def new
  	@job = current_user.jobs.find(params[:job_id])
  end


  def create
  	@job = current_user.jobs.find(params[:job_id])

  	@job.stripe_token = params[:payment][:token]

  	if @job.save

  		# ONE OFF CHARGE
  		# charge this card
  		 Stripe::Charge.create(
  		 	amount: 100, 
  		 	currency: "gbp", 
  			card: @job.stripe_token, 
  		 	description: "Job id: #{@job.id}"
  		 	)

		# # SUBSCRIPTION
		# Stripe::Customer.create(
		# 	card: @job.stripe_token,
		# 	description: "Job id: #{@job.id}"
		# 	plan: "gold"
		# 	)

  		flash[:success] = "Your job is now featured"

  	end
	redirect_to job_path(@job)
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<div class="eight columns offset-by-two">

	<h2>Feature this job</h2>

	<%= form_tag job_payment_path(@job) do |f| %>

		  <span class="payment-errors"></span>

		  <div class="form-row">
		    <label>
		      <span>Card Number</span>
		      <input type="text" size="20" data-stripe="number"/>
		    </label>
		  </div>

		  <div class="form-row">
		    <label>
		      <span>CVC</span>
		      <input type="text" size="4" data-stripe="cvc"/>
		    </label>
		  </div>

		  <div class="form-row">
		    <label>
		      <span>Expiration (MM/YYYY)</span>
		      <input type="text" size="2" data-stripe="exp-month"/>
		    </label>
		    <span> / </span>
		    <input type="text" size="4" data-stripe="exp-year"/>
		  </div>

		  <button type="submit">Submit Payment</button>

	<% end %>

</div>

<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('<%= STRIPE_PUBLIC_KEY %>');
  
  jQuery(function($) {
  $('form').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});

	var stripeResponseHandler = function(status, response) {
	  var $form = $('form');

	  if (response.error) {
	    // Show the errors on the form
	    $form.find('.payment-errors').text(response.error.message);
	    $form.find('button').prop('disabled', false);
	  } else {
	    // token contains id, last4, and card type
	    var token = response.id;
	    // Insert the token into the form so it gets submitted to the server
	    $form.append($('<input type="hidden" name="payment[token]" />').val(token));
	    // and submit
	    $form.get(0).submit();
	  }
	};
</script>