config/routes.rb
Onboard::Application.routes.draw do

  # to fit in with omniauth's callback urls
  get "/auth/:provider/callback" => "social_logins#create"

  # static pages
  get "/about" => "contents#about"
  get "/terms-and-conditions" => "contents#terms", as: "terms"
  get "/privacy" => "contents#privacy"

  # this is where our URLs of our webapp are set
  resources :users
  resources :jobs do
    resources :submissions
    resource :payment
  end


  # because i don't want to login twice as a user
  # lets use a singular resource
  resource :session

  root "jobs#index"

end

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title>Jobs</title>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <header class="row">
    <h1 class="two columns">
      <%= link_to(root_path) do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </h1>

    <nav class="ten columns">

      <% if current_user.present? %>

        <%= link_to current_user.name, "#" %>
        <%= link_to "Add a job", new_job_path %>
        <%= link_to "Account", "#" %>
        <%= link_to "Log out", session_path, method: :delete %>

      <% else %>

        <%= link_to "Log in", new_session_path %>
        <%= link_to "Sign up", new_user_path %>
      
      <% end %>

    </nav>
  </header>

  <% flash.each do |key, value| %>
    <div class="twelve columns flash <%= key %>"><%= value %></div>
  <% end %>

  <article class="row">
    <%= yield %>
  </article>

  <footer>
    <p>&copy; <%= Date.today.year %> Onboard Ltd</p>
  </footer>
</div> <!--  .container -->

</body>
</html>